const $=id=>document.getElementById(id);
function readSaved(){try{return JSON.parse(localStorage.getItem('kotoba-v1'))||{}}catch{return {}}}
const saved=readSaved(); saved.errors??=[];saved.history??=[];
function persist(){try{localStorage.setItem('kotoba-v1',JSON.stringify(saved))}catch{$('feedback').textContent+=' Результат не удалось сохранить в браузере.'}}
const normalize=s=>s.normalize('NFKC').toLowerCase().replace(/ё/g,'е').replace(/[。！？!?.,、]/g,'').replace(/\s+/g,' ').trim();
function shuffle(items){let a=[...items];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function pool(){if($('kind').value==='kanji')return KANJI;return WORDS.filter(w=>({all:true,series:!!w.num,first:w.num&&w.num<=30,new:w.num>30,extra:!w.num,errors:saved.errors.includes(w.id)})[$('pool').value])}
function settings(){const kanji=$('kind').value==='kanji';$('poolLabel').hidden=kanji;$('kanjiLabel').hidden=!kanji;$('direction').parentElement.hidden=kanji;const n=pool().length;$('count').max=Math.max(n,1);$('available').textContent=`Доступно: ${n} ${kanji?'карточек кандзи':'слов'}.`}
['kind','pool'].forEach(id=>$(id).addEventListener('change',settings));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('active',n===b))});
let queue=[],index=0,results=[],checked=false;
function createQuestion(w){const kanji=$('kind').value==='kanji';let mode=kanji?$('kanjiMode').value:$('direction').value;if(mode==='mixed')mode=shuffle(kanji?['meaning','reading','writing']:['jp-ru','ru-jp'])[0];const reverse=['writing','ru-jp'].includes(mode);return {w,mode,prompt:reverse?w.ru[0]:w.jp,answers:mode==='reading'?[w.reading]:reverse?[w.jp,...(w.aliases||[])]:w.ru,kanji}}
$('start').onclick=()=>{const n=Number($('count').value);if(!Number.isInteger(n)||n<1){$('available').textContent='Укажи целое количество от 1.';return}const items=pool();if(!items.length){$('available').textContent='Ошибок пока нет. Выбери другой набор.';return}queue=shuffle(items).slice(0,Math.min(n,items.length)).map(createQuestion);index=0;results=[];$('summary').replaceChildren();show();if(window.matchMedia('(max-width:760px)').matches)document.querySelector('.card-area').scrollIntoView({behavior:'smooth',block:'start'})};
function show(){checked=false;const q=queue[index];$('sessionLabel').textContent=q.kanji?'КАРТОЧКИ КАНДЗИ':'АКТИВНОЕ ВСПОМИНАНИЕ';$('counter').textContent=`${index+1} / ${queue.length}`;$('bar').style.width=`${index/queue.length*100}%`;$('taskLabel').textContent=({meaning:'НАПИШИ РУССКОЕ ЗНАЧЕНИЕ',reading:'НАПИШИ ЧТЕНИЕ КАНОЙ',writing:'НАПИШИ ИЕРОГЛИФ', 'jp-ru':'ПЕРЕВЕДИ НА РУССКИЙ','ru-jp':'НАПИШИ ПО-ЯПОНСКИ'})[q.mode];$('prompt').textContent=q.prompt;$('prompt').classList.toggle('kanji',q.kanji&&q.mode!=='writing');$('subtitle').textContent=q.kanji?'Чтение относится к этому слову':q.w.num?`Слово №${q.w.num}`:'Из прошлой практики';$('answerForm').hidden=false;$('answer').value='';$('answer').disabled=false;$('check').disabled=false;$('unsure').checked=false;$('unsure').disabled=false;$('feedback').textContent='';$('feedback').className='';$('reveal').hidden=false;$('next').hidden=true;$('answer').focus({preventScroll:true})}
function check(reveal=false){if(checked)return;const q=queue[index],answer=$('answer').value;if(!reveal&&!normalize(answer)){$('feedback').textContent='Напиши ответ или нажми «Не помню».';return}checked=true;const ok=!reveal&&q.answers.some(a=>normalize(a).replace(/^[～~]/,'')===normalize(answer).replace(/^[～~]/,''));const unsure=$('unsure').checked;results.push({q,answer,ok,unsure});if(!ok&&!saved.errors.includes(q.w.id))saved.errors.push(q.w.id);if(ok&&!unsure)saved.errors=saved.errors.filter(id=>id!==q.w.id);$('feedback').className=ok?'good':'bad';$('feedback').textContent=`${ok?'Верно.':reveal?'Запомним:':'Пока не совпало.'} ${q.answers.join(' / ')}${q.kanji?` · ${q.w.jp}（${q.w.reading}）`:''}${ok&&unsure?' · Отмечено сомнение.':''}`;$('answer').disabled=true;$('check').disabled=true;$('unsure').disabled=true;$('reveal').hidden=true;$('next').hidden=false;$('next').textContent=index===queue.length-1?'Посмотреть результат →':'Следующая карточка →';persist()}
$('answerForm').onsubmit=e=>{e.preventDefault();check()};$('reveal').onclick=()=>check(true);
$('next').onclick=()=>{index++;if(index<queue.length){show();return}const correct=results.filter(r=>r.ok).length;$('bar').style.width='100%';$('answerForm').hidden=true;$('next').hidden=true;$('feedback').textContent='';$('feedback').className='';$('prompt').textContent=`${correct} / ${queue.length}`;$('prompt').classList.remove('kanji');$('taskLabel').textContent='ПОДХОД ЗАВЕРШЁН';$('subtitle').textContent='Верных ответов сегодня. Устойчивое запоминание проверяется после перерыва.';const difficult=results.filter(r=>!r.ok||r.unsure);$('summary').replaceChildren();const heading=document.createElement('h2');heading.textContent=difficult.length?'Повторить ещё раз':'Все ответы верны в этом подходе';$('summary').append(heading);const list=document.createElement('ul');difficult.forEach(r=>{const li=document.createElement('li');li.textContent=`${r.q.w.jp} — ${r.q.w.ru[0]}${r.q.w.reading?' · '+r.q.w.reading:''}${r.unsure?' · сомнение':''}`;list.append(li)});$('summary').append(list);saved.history.push({date:new Date().toISOString(),total:queue.length,correct,unsure:results.filter(r=>r.unsure).length});saved.history=saved.history.slice(-100);persist();settings()};
function renderWords(){const query=normalize($('search').value);$('wordList').replaceChildren();WORDS.filter(w=>normalize(w.jp+' '+w.ru.join(' ')).includes(query)).forEach(w=>{$('wordList').append(wordCard(w))})}
function wordCard(w){const node=document.createElement('article');node.className='word';const strong=document.createElement('strong');strong.textContent=w.jp;const p=document.createElement('p');p.textContent=w.ru[0]+(w.reading?' · '+w.reading:'');const small=document.createElement('small');small.textContent=(w.num?'№'+w.num+' · ':'')+w.source;const badge=document.createElement('div');badge.className='badge';badge.textContent=w.status;node.append(strong,p,small,badge);return node}
$('search').oninput=renderWords;KANJI.forEach(w=>$('kanjiList').append(wordCard(w)));RULES.forEach(([title,text,example,translation])=>{const a=document.createElement('article');a.className='rule';for(const [tag,value,cls]of [['h2',title,''],['p',text,''],['p',example,'example'],['small',translation,'']]){const el=document.createElement(tag);el.textContent=value;el.className=cls;a.append(el)}$('ruleList').append(a)});settings();renderWords();
